spring:
  main:
    web-application-type: reactive
  banner:
    charset: UTF-8 # Banner file encoding.
    location: classpath:banner.txt # Banner text resource location.

logging:
  level:
    ROOT: ERROR
    com.amway.integration.mashery: INFO
  path: logs
  fileNamePattern: websocket-%i.log
  
log4j:
  logger:
    httpclient.wire.header: TRACE
    httpclient.wire.content: TRACE
    org.apache.commons.http: TRACE
    org.elasticsearch: TRACE
