websocket:
  url: "wss://logstream-api.mashery.com/ecls/subscribe/a335702d-f753-442d-9d78-d0908d0df643/aa166722-a9e2-490f-9ced-ae754d01cda6?key=onCgTueVYrcLsJYNYfEvzlXfyPSJPuEUDzK"
  asynctimeoutms: 60000
  sessiontimeoutms: 60000
  pingtimems: 600000
logging:
  level:
    root: "off"
spring:
  main:
    banner-mode: "off"